### ISSUE TITLE
ValueError: Unsupported ONNX opset version: 17

### ISSUE THREAD

**Issue by yxl502** [vjsrinivas/siammask_onnx#1]
what the verson about yours?

**Comment by vjsrinivas** [comment]
Hi @yxl502, can you give more context to your error?
I'm running `onnx==1.14.1` and `onnxruntime==1.14.0`. I'll be working on getting a conda environment yaml file out soon for better reproducibility. For now, reduce opset number to something that your ONNX version supports.

**Comment by vjsrinivas** [comment]
Added explicit onnx version in https://github.com/vjsrinivas/siammask_onnx/commit/3db7834a2a7ffe1f47d1209f073872f825631603

Not sure if creating a conda environment file is necessary since most of the requirements follow the original SiamMask repo with some extra packages that are pip installed.
